### ISSUE TITLE
Extension not working, how to debug?

### ISSUE THREAD

**Issue by Lucretiel** [rolandostar/tabletopsimulator-lua-vscode#15] opened 2020-11-26 21:04 UTC
When running `Get Lua Scripts`, I get the error `Command 'TTSLua: Get Lua Scripts' resulted in an error (command 'ttslua.getScripts' not found)`. There doesn't seem to be any other context available, so I'm not sure how to go about debugging.

VSCode 1.51.1
Tabletop Simulator Lua 1.1.1, installed from the extension marketplace

**Comment by rolandostar** [comment] 2020-11-26 21:20
On the terminal panel, at the output tab > Log (Extension Host). Would you please send me the log when this issue occurs?

**Comment by Lucretiel** [comment] 2020-11-26 22:48
Thank you! Here's the error log:

```
[2020-11-26 17:47:10.365] [exthost] [info] ExtensionService#_doActivateExtension rolandostar.tabletopsimulator-lua {"startup":false,"extensionId":{"value":"rolandostar.tabletopsimulator-lua","_lower":"rolandostar.tabletopsimulator-lua"},"activationEvent":"onCommand:ttslua.getScripts"}
[2020-11-26 17:47:10.365] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Lucre/.vscode/extensions/rolandostar.tabletopsimulator-lua-1.1.1/dist/extension.js
[2020-11-26 17:47:10.424] [exthost] [error] Activating extension rolandostar.tabletopsimulator-lua failed due to an error:
[2020-11-26 17:47:10.494] [exthost] [error] Error: Cannot invoke loadWASM more than once.
	at Object.t.loadWASM (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\vscode-oniguruma\release\main.js:1:4823)
	at Object.829 (c:\Users\Lucre\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.1\dist\extension.js:9306:38)
	at __webpack_require__ (c:\Users\Lucre\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.1\dist\extension.js:9416:42)
	at Object.603 (c:\Users\Lucre\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.1\dist\extension.js:4090:20)
	at __webpack_require__ (c:\Users\Lucre\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.1\dist\extension.js:9416:42)
	at Object.112 (c:\Users\Lucre\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.1\dist\extension.js:3926:22)
	at __webpack_require__ (c:\Users\Lucre\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.1\dist\extension.js:9416:42)
	at c:\Users\Lucre\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.1\dist\extension.js:9439:18
	at Object.<anonymous> (c:\Users\Lucre\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.1\dist\extension.js:9440:12)
	at Module.i._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:17:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1064:776)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1034:665)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1030:844)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:34:963)
	at p._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1035:939)
	at p._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:932:27)
	at p._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:930:946)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 0)
```

**Comment by rolandostar** [comment] 2020-11-26 22:59
Thank you, I'm thinking this is caused by a conflicting extension. Could you please run this command in a terminal?

`code --list-extensions`

**Comment by Lucretiel** [comment] 2020-11-26 23:05
Sure thing:

```
bungcip.better-toml
CoenraadS.bracket-pair-colorizer-2
esbenp.prettier-vscode
Gruntfuggly.todo-tree
kevinkyang.auto-comment-blocks
matklad.rust-analyzer
ms-azuretools.vscode-docker
ms-python.python
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-wsl
ms-vscode.cpptools
ms-vscode.powershell
ms-vscode.vscode-typescript-tslint-plugin
rolandostar.tabletopsimulator-lua
streetsidesoftware.code-spell-checker
yzane.markdown-pdf
```

I assumed that rust-analyzer would be the most likely cause of WASM issues, but I confirmed that the issue still appears when I disable it.

**Comment by rolandostar** [comment] 2020-11-26 23:31
I believe it's caused by conflict with `CoenraadS.bracket-pair-colorizer-2`
I'll continue investigating this issue.

**Comment by Lucretiel** [comment] 2020-11-26 23:38
I'll disable and see if that fixes it. I'm almost certain that's not it, though, only because I recently set up my brother's laptop, and the *only* extensions he has are BPC2 and Tabletop Simulator, and it's working fine on his system.

**Comment by Lucretiel** [comment] 2020-11-26 23:40
Oh, that seems to have fixed it.

**Comment by rolandostar** [comment] 2020-11-26 23:50
I'll close this issue for now, even though I don't understand fully how that extension causes an issue, I'll keep digging and am open to implement any suggested changes that would fix this permanently. Thanks for the report.

**Closed by rolandostar** 2020-11-26 23:50 UTC

**Comment by ChildishGiant** [comment] 2021-04-06 21:47
Just bumped into this. Maybe detection for when this extension is enabled?

**Comment by snebjorn** [comment] 2021-04-12 19:16
@rolandostar perhaps mention this in the README, I spent a few evenings with this issue :)

**Comment by KorvinSzanto** [comment] 2022-02-12 22:35
I'm seeing this same issue in a dev container with only `rolandostar.tabletopsimulator-lua` installed
